Implement a basic HTTP exporter
m-lab/murakami pull request #65
Opened 2020-05-27 10:11 UTC by robertodauria

This PR adds a new exporter (`type="http"`) which sends the JSON output of a test to an HTTP endpoint via a POST request. 

The format of the JSON object is:
```
{
    "apiVersion": 1,
    "data": { <Murakami output JSON> }
}
```

It also includes some fairly basic unit tests for this exporter.

Since there is no authentication method on the upload service prototype yet, the only configuration parameter for this exporter type is `url`. E.g.
```
[exporters.http]
type = "http"
enabled = true
url = "http://some-url/api/v1/runs"
```

2020-05-28 13:04 UTC, critzo commented
Let's wait to merge this until we have an API with authentication to test it with.

2020-05-29 09:18 UTC, robertodauria commented
Of course, no rush! I've pushed a small bugfix to make it work with the (non-authenticated) prototype, meanwhile.

2020-09-28 14:07 UTC, jheretic requested changes
Based on testing, should work with the suggested fix (and potentially with other changes already in `master`).

2020-09-28 14:07 UTC, jheretic commented on murakami/exporters/http.py
> +        resp = requests.post(self._url, data=json.dumps(json_data))
This should be `resp = requests.post(self._url, json=json_data)`, or else the content-type header won't be set correctly to `content/json` and the data won't be parsed.

2020-09-28 14:16 UTC, jheretic approved these changes

2020-09-28 14:19 UTC, merged